-- ModernWeb - Script Supabase complet (version corrigée)
-- Exécute ce script dans Supabase SQL Editor

-- 1) Nettoyage
DROP TABLE IF EXISTS client_briefs;
DROP TABLE IF EXISTS projects;

-- 2) Table projects (avec toutes les colonnes)
CREATE TABLE public.projects (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         text        NOT NULL,
  client_type   text        NOT NULL DEFAULT 'particulier' CHECK (client_type IN ('particulier','professionnel')),
  project_type  text        NOT NULL DEFAULT 'site_vitrine',
  theme         text        NOT NULL DEFAULT 'default',
  short_desc    text        NOT NULL,
  description   text        NOT NULL,
  technologies  text[]      NOT NULL DEFAULT '{}',
  project_date  date        NOT NULL,
  status        text        NOT NULL CHECK (status IN ('en_cours','termine','publie')),
  featured      boolean     NOT NULL DEFAULT false,
  link          text,
  cover_image   text,
  gallery       text[]      NOT NULL DEFAULT '{}',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- 3) Table client_briefs (PDF)
CREATE TABLE public.client_briefs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name   text        NOT NULL,
  client_email  text        NOT NULL,
  project_type  text        NOT NULL,
  submitted_at  timestamptz NOT NULL DEFAULT now(),
  pdf_url       text        NOT NULL,
  status        text        NOT NULL DEFAULT 'nouveau' CHECK (status IN ('nouveau','consulte','archive')),
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- 4) Index
CREATE INDEX idx_projects_status_date ON public.projects(status, project_date DESC);
CREATE INDEX idx_projects_featured ON public.projects(featured);
CREATE INDEX idx_client_briefs_status ON public.client_briefs(status);
CREATE INDEX idx_client_briefs_date ON public.client_briefs(submitted_at DESC);

-- 5) RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_briefs ENABLE ROW LEVEL SECURITY;

-- 6) Policies (authentifié)
CREATE POLICY "projects_select_auth" ON public.projects FOR SELECT TO authenticated USING (true);
CREATE POLICY "projects_insert_auth" ON public.projects FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "projects_update_auth" ON public.projects FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "projects_delete_auth" ON public.projects FOR DELETE TO authenticated USING (true);

CREATE POLICY "client_briefs_select_auth" ON public.client_briefs FOR SELECT TO authenticated USING (true);
CREATE POLICY "client_briefs_insert_auth" ON public.client_briefs FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "client_briefs_update_auth" ON public.client_briefs FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "client_briefs_delete_auth" ON public.client_briefs FOR DELETE TO authenticated USING (true);

-- 7) Politique pour lecture publique des projets (site public)
CREATE POLICY "projects_select_anon" ON public.projects FOR SELECT TO anon USING (true);

-- 8) Trigger updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON public.projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 9) Seed projets (avec project_type et theme)
INSERT INTO public.projects
  (title, client_type, project_type, theme, short_desc, description, technologies, project_date, status, featured, link, cover_image, gallery)
VALUES
  (
    'Les Jardins de Marie',
    'professionnel',
    'site_vitrine',
    'nature',
    'Des légumes cultivés avec passion dans les Hauts-de-France.',
    'Site vitrine + e-commerce pour mettre en avant des produits bio récoltés à la main.',
    ARRAY['HTML','CSS','JavaScript'],
    '2024-03-01',
    'publie',
    true,
    'https://milann-lede.github.io/les-jardins-de-marie/',
    'https://modernweb.fr/images/jardins_de_marie.webp',
    ARRAY[]::text[]
  ),
  (
    'Digital Planner Lisa',
    'professionnel',
    'ecommerce',
    'tech',
    'Un planificateur numérique esthétique et fonctionnel.',
    'E-commerce pour vendre un planner digital, avec mise en avant produit et tunnel d''achat.',
    ARRAY['HTML','CSS','JavaScript'],
    '2024-02-01',
    'publie',
    true,
    'https://milann-lede.github.io/Digitale-planer-lisa/',
    'https://modernweb.fr/images/digital_planner.webp',
    ARRAY[]::text[]
  ),
  (
    'Mauger Débarras Service',
    'professionnel',
    'site_vitrine',
    'default',
    'Site de présentation pour une entreprise de débarras et nettoyage.',
    'Site vitrine en cours de construction pour présenter les services de débarras.',
    ARRAY['HTML','CSS','JavaScript'],
    '2024-04-01',
    'en_cours',
    false,
    NULL,
    'https://modernweb.fr/images/mauger_construction.png',
    ARRAY[]::text[]
  );

-- 10) Créer le bucket storage pour les images (si pas déjà fait manuellement)
-- Note: Cette partie doit parfois être faite manuellement dans Supabase Dashboard > Storage

-- Insérer le bucket dans storage.buckets s'il n'existe pas
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 11) Policies pour le storage (images publiques)
-- Supprimer les anciennes policies si elles existent
DROP POLICY IF EXISTS "Public read project images" ON storage.objects;
DROP POLICY IF EXISTS "Auth upload project images" ON storage.objects;
DROP POLICY IF EXISTS "Auth update project images" ON storage.objects;
DROP POLICY IF EXISTS "Auth delete project images" ON storage.objects;

-- Permettre à tout le monde de VOIR les images
CREATE POLICY "Public read project images" ON storage.objects 
FOR SELECT USING (bucket_id = 'project-images');

-- Permettre aux utilisateurs authentifiés d'UPLOADER des images
CREATE POLICY "Auth upload project images" ON storage.objects 
FOR INSERT WITH CHECK (bucket_id = 'project-images');

-- Permettre aux utilisateurs authentifiés de MODIFIER des images
CREATE POLICY "Auth update project images" ON storage.objects 
FOR UPDATE USING (bucket_id = 'project-images');

-- Permettre aux utilisateurs authentifiés de SUPPRIMER des images
CREATE POLICY "Auth delete project images" ON storage.objects 
FOR DELETE USING (bucket_id = 'project-images');

-- 12) Policies pour les briefs (Accès ANONYME pour les prospects)

-- Supprimer les anciennes policies si elles existent
DROP POLICY IF EXISTS "Anon insert client briefs" ON public.client_briefs;
DROP POLICY IF EXISTS "Anon upload brief pdf" ON storage.objects;
DROP POLICY IF EXISTS "Anon select brief pdf" ON storage.objects;

-- Permettre aux anonymes d'insérer des briefs (formulaire prospect)
CREATE POLICY "Anon insert client briefs" ON public.client_briefs
FOR INSERT TO anon WITH CHECK (true);

-- Permettre aux anonymes d'uploader leur PDF dans le dossier briefs/
CREATE POLICY "Anon upload brief pdf" ON storage.objects
FOR INSERT TO anon WITH CHECK (
  bucket_id = 'project-images' AND 
  (storage.foldername(name))[1] = 'briefs'
);

-- Permettre aux anonymes de voir leur propre PDF (ou tout PDF public dans briefs/)
CREATE POLICY "Anon select brief pdf" ON storage.objects
FOR SELECT TO anon USING (
  bucket_id = 'project-images' AND 
  (storage.foldername(name))[1] = 'briefs'
);

-- ==========================================
-- 13) TABLE REVIEWS (Avis clients)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.reviews (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text        NOT NULL,
  role          text        DEFAULT 'Client',
  message       text        NOT NULL,
  rating        integer     NOT NULL DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  avatar_url    text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Index pour tri par date
CREATE INDEX IF NOT EXISTS idx_reviews_date ON public.reviews(created_at DESC);

-- RLS pour reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Tout le monde peut LIRE les avis (site public)
CREATE POLICY "reviews_select_all" ON public.reviews 
FOR SELECT USING (true);

-- Les anonymes peuvent AJOUTER des avis (formulaire public)
CREATE POLICY "reviews_insert_anon" ON public.reviews 
FOR INSERT TO anon WITH CHECK (true);

-- Les authentifiés peuvent aussi ajouter/modifier/supprimer
CREATE POLICY "reviews_insert_auth" ON public.reviews 
FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "reviews_update_auth" ON public.reviews 
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "reviews_delete_auth" ON public.reviews 
FOR DELETE TO authenticated USING (true);

-- ==========================================
-- 14) BUCKET AVATARS (Photos des avis)
-- ==========================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policies pour le bucket avatars
DROP POLICY IF EXISTS "Public read avatars" ON storage.objects;
DROP POLICY IF EXISTS "Anon upload avatars" ON storage.objects;
DROP POLICY IF EXISTS "Auth delete avatars" ON storage.objects;

-- Tout le monde peut voir les avatars
CREATE POLICY "Public read avatars" ON storage.objects 
FOR SELECT USING (bucket_id = 'avatars');

-- Les anonymes peuvent uploader leur avatar
CREATE POLICY "Anon upload avatars" ON storage.objects 
FOR INSERT TO anon WITH CHECK (bucket_id = 'avatars');

-- Les authentifiés peuvent supprimer
CREATE POLICY "Auth delete avatars" ON storage.objects 
FOR DELETE TO authenticated USING (bucket_id = 'avatars');
